// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-nB05tCiy8-kqtfgeVqNTnTNUd4BBn98',
    appId: '1:559106793239:web:84c5dc92be519097742152',
    messagingSenderId: '559106793239',
    projectId: 'stornix-59419',
    authDomain: 'stornix-59419.firebaseapp.com',
    storageBucket: 'stornix-59419.firebasestorage.app',
    measurementId: 'G-CQM6JDBDH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Oyv-F4q6E7DH-eZnM0WJAwXX_eiM2pk',
    appId: '1:559106793239:android:258bdc8bf78a99d9742152',
    messagingSenderId: '559106793239',
    projectId: 'stornix-59419',
    storageBucket: 'stornix-59419.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3dzJKUqjh2QLm8NjZ4PsCzil2UX_Vhtk',
    appId: '1:559106793239:ios:b9069e6c316c84c2742152',
    messagingSenderId: '559106793239',
    projectId: 'stornix-59419',
    storageBucket: 'stornix-59419.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3dzJKUqjh2QLm8NjZ4PsCzil2UX_Vhtk',
    appId: '1:559106793239:ios:b9069e6c316c84c2742152',
    messagingSenderId: '559106793239',
    projectId: 'stornix-59419',
    storageBucket: 'stornix-59419.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-nB05tCiy8-kqtfgeVqNTnTNUd4BBn98',
    appId: '1:559106793239:web:f2ca5482e059ca15742152',
    messagingSenderId: '559106793239',
    projectId: 'stornix-59419',
    authDomain: 'stornix-59419.firebaseapp.com',
    storageBucket: 'stornix-59419.firebasestorage.app',
    measurementId: 'G-7MG62CW0Z6',
  );
}
